### PR TITLE
Add Appveyor CI configuration

### PR DESCRIPTION
**Pull request by danieldk**
This adds CI builds for Windows. As an additional benefit it extracts artifacts, so we can also upload wheels to PyPI.

For now, I don't want to upload artifacts automatically. We could do that once we are happy with the automatic builds.

### CODE REVIEW

**Comment by sebpuetz** [comment]
Unsure how to review this, but I guess I'll give it a go to run on my Windows install later?

**Comment by danieldk** [comment]
> Unsure how to review this, but I guess I'll give it a go to run on my Windows install later?

There is nothing to test on a Windows install. I'll just merge it then ;).

**Comment by danieldk** [comment]
> Unsure how to review this, but I guess I'll give it a go to run on my Windows install later?

If you do happen to have a Windows machine, it would be nice if you could test if the artifacts (or at least the one for your Python version) built by Appveyor work:

https://ci.appveyor.com/project/danieldk/finalfusion-python/builds/23304082/artifacts

If so, I could upload them to PyPI, so that we have the Windows wheel `pip`-installable as well.

**Comment by sebpuetz** [comment]
That's kind of what I meant earlier, I was going to build the wheel on my Windows partition and then try to use it there. If you think that's unnecessary work, I'll just use the wheel built by appveyor (or get it from pypi if you upload it there). I should find some time for that later tonight or some time tomorrow.

**Comment by danieldk** [comment]
The wheel builds. It builds on appveyor and Michael (from the word repr course) also got it to build on Windows by hand. I am especially curious if the appveyor artifacts work properly/.

Thanks for trying it!

**Comment by sebpuetz** [comment]
I installed and tested the 3.7 wheel under 3.7.2 on Win10, worked without problems.

Both mmap and array worked fine.

**Comment by danieldk** [comment]
Awesome!

**Pull request merged**
