### PR TITLE
Update pyo3 to 0.8.

### PR DESCRIPTION
**Pull request by sebpuetz**
Prerequisite for fixing #51

### CODE REVIEW

**Comment by sebpuetz** [comment]
I'm confused by the CI failures:
- `TryFrom` is stable since `1.34`
- [`NonZeroI*`are stable since `1.34`](https://doc.rust-lang.org/src/core/num/mod.rs.html#110)

rustc version is 1.34, yet CI fails and I can't build locally either with the same toolchain.

**Comment by sebpuetz** [comment]
pyo3 requires `nightly-2019-07-19-x86_64-unknown-linux-gnu` on `0.8`

**Review by danieldk — COMMENTED** [review]
Looks good, but do we need all the updates in `Cargo.lock`? Or are they enforced by the pyo3 update? Seems like a lot of updates.

**Comment by danieldk** [comment]
> Looks good, but do we need all the updates in `Cargo.lock`? Or are they enforced by the pyo3 update? Seems like a lot of updates.

Seems like there are more errors (CI fail).

**Comment by sebpuetz** [comment]
> Looks good, but do we need all the updates in `Cargo.lock`? Or are they enforced by the pyo3 update? Seems like a lot of updates.

~~Looks like the rust plugin for CLion was doing its thing again.~~ nevermind, just running `pyo3-pack build --release` changes a lot in `Cargo.lock`

> Seems like there are more errors (CI fail).

I forgot to change the default toolchain, I had only updated the required rust version for travis-ci.

**Review by danieldk — APPROVED** [review]
Sorry for the slow ack. I was fighting my own Rust battles ;).

**Pull request merged**
