### PR TITLE
Split lib.rs into several modules

### PR DESCRIPTION
**Pull request by danieldk**
`lib.rs` was getting a bit large and unwieldy.

### CODE REVIEW

**Comment by sebpuetz** [comment]
Makes sense to do this. While looking over the changes I noticed that I forgot documentation for the item_to_indices method. Also I took a look at the docstrings generated from our module, they are not quite the usual python documentation.

in IPython:
```
import finalfusion
finalfusion.Embeddings.embedding?
Docstring:
Get the embedding for the given word.

If the word is not known, its representation is approximated
using subword units.
```

I'd suggest that we address that in a new PR soon-ish and maybe cut a new release with added norms support too then.

**Review by sebpuetz — APPROVED** [review]
Looks fine, what's the motivation to separate Embeddings from EmbeddingsWrap?

**Comment by danieldk** [comment]
> Looks fine, what's the motivation to separate Embeddings from EmbeddingsWrap?

Only minor: the embeddings module is already very large.

**Comment by danieldk** [comment]
> Makes sense to do this. While looking over the changes I noticed that I forgot documentation for the item_to_indices method. Also I took a look at the docstrings generated from our module, they are not quite the usual python documentation.
> 
> in IPython:
> 
> ```
> import finalfusion
> finalfusion.Embeddings.embedding?
> Docstring:
> Get the embedding for the given word.
> 
> If the word is not known, its representation is approximated
> using subword units.
> ```
> 
> I'd suggest that we address that in a new PR soon-ish and maybe cut a new release with added norms support too then.

Good idea!

**Pull request merged**
