### PR TITLE
Nix buildPythonPkg with pyproject.toml

### PR DESCRIPTION
**Pull request by sebpuetz**
`nix-shell -p 'import ./. {}'`

Builds the package, runs tests and drops me into a shell where I can import & use the package. Found at https://nixos.org/nixpkgs/manual/#python 15.17.2.2.1.1

### CODE REVIEW

**Comment by danieldk** [comment]
What Nix channel are you on? As I mentioned on Slack yesterday, this works for me with `default.nix` as is, which it should, because this is also a `setuptools` project.

At any rate, there is still a weird issue, because just `nix-shell` should work as well. But it only works when there is no `pyproject.toml`.

```
$ rm pyproject.toml 
$ nix-shell
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Executing setuptoolsShellHook
Obtaining file:///home/daniel/git/finalfusion-python
Requirement already satisfied: numpy in /nix/store/hs1m7mwrz8nmkknc7la7qvdqrmw4f9vi-python3.7-numpy-1.18.4/lib/python3.7/site-packages (from finalfusion==0.7.0rc0) (1.18.4)
Requirement already satisfied: toml in /nix/store/2kqr6kyj9mfkz9pmd477s37fgbz7dm2x-python3.7-toml-0.10.0/lib/python3.7/site-packages (from finalfusion==0.7.0rc0) (0.10.0)
Installing collected packages: finalfusion
  Running setup.py develop for finalfusion
Successfully installed finalfusion
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/bin/python3.7 -m pip install --upgrade pip' command.
Finished executing setuptoolsShellHook

[nix-shell:~/git/finalfusion-python]$ pytest
============================= test session starts ==============================
platform linux -- Python 3.7.7, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/daniel/git/finalfusion-python
collected 83 items                                                             

tests/test_analogies.py .                                                [  1%]
tests/test_compat.py .......                                             [  9%]
tests/test_embeddings.py ....................                            [ 33%]
tests/test_io.py ...                                                     [ 37%]
tests/test_metadata.py ....                                              [ 42%]
tests/test_norms.py ......                                               [ 49%]
tests/test_similarity.py ....                                            [ 54%]
tests/test_storage.py ..............                                     [ 71%]
tests/test_subwords.py .......                                           [ 79%]
tests/test_test_setup.py ..                                              [ 81%]
tests/test_vocab.py ...............                                      [100%]

============================== 83 passed in 0.74s ==============================
```

We should get that working, because it avoids creating a new store path for each `nix-shell` invocation.

**Comment by sebpuetz** [comment]
Closing this, since it doesn't seem to have any effect anyways?

**Comment by danieldk** [comment]
I think it would still be nice to have this change, since it seems that pyproject projects are the future.

**Comment by sebpuetz** [comment]
Then, here we go again ;)

**Review by danieldk — APPROVED** [review]

**Review by danieldk — APPROVED** [review]

**Pull request merged**
