### PR TITLE
Add masked analogy functionality.

### PR DESCRIPTION
**Pull request by sebpuetz**
Also requires a bump of the `finalfusion` dependency

### CODE REVIEW

**Review by danieldk — COMMENTED** [review]
Any chance you could add a unit test? Perhaps you could use `analogy.bin` from `finalfusion-rust`.

**Comment by sebpuetz** [comment]
I pretty much copied the unit test from ff-rust, although I had to convert to finalfusion embeddings since I think that we can't read w2v format from Python.

**Comment by danieldk** [comment]
Excellent! Though now the mask is not tested, maybe you could add a query like

"Paris", "Frankreich", "Paris"

And in/exclude the second word to verify that both inclusion and exclusion work?

**Comment by sebpuetz** [comment]
> Excellent! Though now the mask is not tested, maybe you could add a query like
> 
> "Paris", "Frankreich", "Paris"
> 
> And in/exclude the second word to verify that both inclusion and exclusion work?

I'll look up some of the nearest neighbors with the offsets, I don't want to use the method to figure out what the results should be. I'll also make a PR in ff-rust soon, since we're not testing it over there either.

**Comment by sebpuetz** [comment]
Oops, I misread your query. I didn't recognize Paris showed up twice!

**Review by danieldk — APPROVED** [review]

**Pull request merged**
